박명규 - 미션 1. 자동차 경주
talmood/java-racingcar pull request #2
Opened 2024-04-28 09:22 UTC by audrb96

## 🚀 기능 요구 사항
초간단 자동차 경주 게임을 구현한다.

주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
- 각 자동차에 이름을 부여할 수 있다. 전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
- 자동차 이름은 쉼표(,)를 기준으로 구분하며 이름은 5자 이하만 가능하다.
- 사용자는 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
- 전진하는 조건은 0에서 9 사이에서 무작위 값을 구한 후 무작위 값이 4 이상일 경우이다.
- 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한 명 이상일 수 있다.
- 우승자가 여러 명일 경우 쉼표(,)를 이용하여 구분한다.
- 사용자가 잘못된 값을 입력할 경우 IllegalArgumentException을 발생시킨 후 애플리케이션은 종료되어야 한다.

2024-04-29 15:10 UTC, sc0116 reviewed
안녕하세여  킬리안 저 짱군데여
무플 방지 목적으로 코멘트 하나 달았슴다!(내일도 무플이면 풀 리뷰 달겠슴다)

이번 미션 남은 기간(화, 수) 동안 저랑 같이 어떤 부분을 테스트해야 하고 어떻게 테스트해야 하는지 같이 고민해보죠!

2024-04-29 15:10 UTC, sc0116 commented on src/test/java/racingcar/CommaStringSplitterTest.java
> +        assertThat(split).containsOnly("pobi", "woni", "jun");
assertThat을 여러개 작성하는 것과 한 묶음으로 테스트를 실행하는 것 두 가지 방법이 테스트 측면에서 어떤 차이가 있는지 고민해보면 좋을 것 같아요!

만약 어렵다면 답글 달아주세요! 같이 고민해봐요

2024-04-30 00:55 UTC, audrb96 commented on src/test/java/racingcar/CommaStringSplitterTest.java
> +        assertThat(split).containsOnly("pobi", "woni", "jun");
assertAll()을 말씀하시는 걸까요??

2024-04-30 00:58 UTC, sc0116 commented on src/test/java/racingcar/CommaStringSplitterTest.java
> +        assertThat(split).containsOnly("pobi", "woni", "jun");
네 맞아유!

2024-05-01 04:32 UTC, shonhyeongy commented on src/main/java/racingcar/Application.java
> +        RacingCars readyRacingCars = racingGamePlayer.ready();
readyRacingCars, playedRacingCars  각 객체들이 리턴을 되어 밖에서 파라미터로 다시 넘겨주는  이유가   있을까요?
 내부  함수에서 처리가  되면  어떨까요?

2024-05-01 04:32 UTC, shonhyeongy commented on src/main/java/racingcar/Location.java
> +    public Location forward() {
Location class 는 위치나 정보를  갖고  있을것 같습니다.
그런데 forward 함수는  자동차의  행위에 가까워  보입니다.
자동차 class가  forward 메소드를  갖고  location class에는 update,  change 라는  메소드를  추가해서
호출하는게 어떨까용?

2024-05-01 06:56 UTC, audrb96 commented on src/main/java/racingcar/Location.java
> +    public Location forward() {
update, change는 변경한다라는 의미가 강합니다.
따라서 앞으로 한칸이 아니라 여러칸, 뒤로 갈 수도 있다하는 의미를 내포합니다. setter와 다를게 없죠.
이렇게 여러 가능성을 열어 둠으로써 오류의 가능성을 열어 두기보다는
앞으로 한칸만 옮길 수 있는 함수만을 작성하는게 옳다고 생각합니다. forward()라는 의미가 애매하다면 다른 함수명을 고민해봐야겠네요!

2024-05-01 07:06 UTC, audrb96 commented on src/main/java/racingcar/Application.java
> +        RacingCars readyRacingCars = racingGamePlayer.ready();
음.. 이렇게 생각하면 어떨까요!
만약에 데이터베이스가 연동이되서 준비가 완료된 자동차의 정보, 게임이 완료된 자동차의 정보를 저장해야 한다고하면 DB에 저장하는 행위까지 player가 해야할까요?? 
player의 역할은 게임을 플레이하는 것에만 집중해야하고 다른 역할은 할 필요가 없습니다
따라서 이렇게 player의 행동을 정의하고 행동의 결과를 return해준다면 player가 책임지지 않아도 되는 행위(위에서 예를 든 DB저장과 같은)를 다른 클래스가 맡아서 할 수 있습니다. 책임을 나눌 수 있는 것이죠!

JPA의 repository.save() 레포지토리가 해야하는 저장의 역할만 하고 저장된 값을 return하면 그 이후 행위는 다른 클래스가 맡아서 하는 것 처럼요

2024-05-01 15:29 UTC, haero77 commented on src/main/java/racingcar/Application.java
> +        RacingCars readyRacingCars = racingGamePlayer.ready();
@audrb96 

`racingGamePlayer.ready();`를 Application 의 정적 메서드에서 호출해야할까라는 의문이 듭니다!
Application 의 main에서는 어떤 작업들을 할 것인지에 대한 킬리안의 기준이 궁금해요 :)

2024-05-01 15:32 UTC, haero77 commented on src/main/java/racingcar/Location.java
> +    public Location forward() {
@audrb96 

Location이라는 클래스명 자체가 많이 포괄적이라는 느낌이 듭니다!
물론 이게 자동차 경주 미션이고, 또 racingcar 패키지에 있으니까 자동차의 위치구나라고 '추측'은 할 수 있지만, 
'추측'해야하는 것과 클래스 이름 그 자체로 의미가 좁혀진 것은 명확한 차이가 있다고 생각해요~!
애플리케이션 규모가 커지면 Location 만 볼 때 그래서 이게 뭐였더라~ 라는 상황이 저는 자주 발생했거든요 ㅎㅎ

적절한 네이밍을 같이 고민해보시죠~!

2024-05-01 15:48 UTC, haero77 requested changes
킬리안 안녕하세요~! 리뷰어 해로입니다!
지나가다가 가볍게 리뷰 남겨봤으니 확인해주세요~!

2024-05-01 15:48 UTC, haero77 commented on src/main/java/racingcar/CommaStringSplitter.java
> +}
StringSplitter를 정적 유틸 클래스가 아닌 '객체'로 만든 이유가 궁금합니다 :)

2024-05-01 15:48 UTC, haero77 commented on src/main/java/racingcar/CarName.java
> +
(코드 스타일)
어떤 클래스는 클래스 다음에 빈 줄이 있고, 어떤 클래스는 빈 줄이 없어요. 
IntelliJ의 Code Style 기능과 코드 정렬 기능을 적극 활용하는 것을 적극 추천 드립니다!

2024-05-01 15:48 UTC, haero77 commented on src/main/java/racingcar/CarName.java
> +    }
(네이밍)
boolean을 리턴하는 메서드의 네이밍에 부정어는 지양됩니다! boolean을 리턴하는 메서드명의 좋은 예를 같이 찾아보시죠!

2024-05-01 15:48 UTC, haero77 commented on src/main/java/racingcar/CarName.java
> +    }
생성자 대신 팩토리 메서드를 사용하신 이유가 있을까요?
킬리안의 팩토리 메서드 사용 기준이 궁금합니다!

2024-05-01 15:48 UTC, haero77 commented on src/main/java/racingcar/CollectionUtils.java
> +}
(접근 제어)

정적 유틸 클래스의 생성자가 public으로 선언되어 있군요! 
이럼 다른 사람이 실수로 이 클래스의 인스턴스를 생성해버릴지도 모른답니다(?)

2024-05-01 15:48 UTC, haero77 commented on src/main/java/racingcar/MoveForwardCondition.java
> +public interface MoveForwardCondition {
추상 메서드가 하나만 있는 인터페이스는 문법적으로는 함수형 인터페이스이긴하죠.
그래서 이 애노테이션을 달아두신 것 같고요 :)

그런데 과연 **다형성을 위해서 우리가 정의한 인터페이스의 메서드가 꼭 하나로 고정될 거라고 보장**할 수 있을까요? 

인터페이스에 기능을 하나 더 붙이기 위해서 메서드를 하나 더 추가하게 되면 그 때 어떤 일이 생길 지 고민해보셔도 좋을 것 같습니다!

2024-05-01 15:48 UTC, haero77 commented on src/main/java/racingcar/RacingCar.java
> +    private final MoveForwardCondition moveForwardCondition;
(가독성, 취향)

취향이긴 한데, static과 인스턴스 필드간에는 저는 한 줄씩 띄어놓습니다. 성격이 아주 다른 친구들이라서요!

2024-05-01 15:48 UTC, haero77 commented on src/main/java/racingcar/RacingCar.java
> +    }
(관심사)

UI 로직이 핵심 객체의 기능으로 선언되어있군요!
이럴 경우 어떤 문제가 있을 수 있을까요?

2024-05-01 15:48 UTC, haero77 commented on src/main/java/racingcar/RacingCar.java
> +    }
메시지 전달이 연쇄적으로 일어나고 있군요 👍

2024-05-01 15:48 UTC, haero77 commented on src/main/java/racingcar/RacingGameNavigation.java
> +public class RacingGameNavigation {
이 클래스 역시 마음껏 인스턴스 생성이 가능하겠군요!

2024-05-01 15:48 UTC, haero77 commented on src/main/java/racingcar/RacingGameNavigation.java
> +}
(네이밍, 취향)

전 상수의 모음이면 확실하게 XXXConstant 이렇게 네이밍 하는게 가독성이 괜찮더라고요.
정적 유틸 클래스의 접미사로 `Utils`를 사용하는 것 처럼요 :)

2024-05-02 00:57 UTC, audrb96 commented on src/main/java/racingcar/Application.java
> +        RacingCars readyRacingCars = racingGamePlayer.ready();
@haero77 
해로님 안녕하세요!
처음 구현할때는 비즈니스 레이어의 구현부라고 생각했습니다.
MVC 패턴으로 보면 컨트롤러에서 서비스로 들어온 직후의 프로세스로요
근데 짱구님이나 다른 분들 구현하신 걸보니, 미션내에서 프레젠테이션레이어와 비즈니스레이어를 나누어야 겠다고 생각이 들어서
다음 미션때는 main()에서 프레젠테이션 역할의 함수, 비즈니스레이어의 호출 함수를 나누어서 개발해볼까 생각해보고 있었습니다.

2024-05-02 01:07 UTC, audrb96 commented on src/main/java/racingcar/Location.java
> +    public Location forward() {
@haero77 
CarPosition, CarLocation 처럼 도메인 명을 앞에 붙여주는 방법도 생각해봤지만
도메인별로 패키지를 나누어볼까 라는 생각도 들더라구요. 
예를 들면
racingcar클래스는 domain.racingcar 안에
Location클래스는  domain.racingcar.vo 안에 구현하는 방식으로요!

2024-05-02 01:15 UTC, audrb96 commented on src/main/java/racingcar/CommaStringSplitter.java
> +}
@haero77 
이 객체는 사실 Array로 변환되는 split() 함수를 List로 반환하기 위해서 만든 목적이 큽니다.
객체로 만든 이유는 Comma(,)가 아닌 다른 String으로 split하거나 좀 더 복잡한 String 분리 과정이 있는 경우를 생각했습니다.
해당 인터페이스를 상속해서 다른 구현체를 구현할 수 있도록요.
다른 String으로 split하는 경우는 delimiter를 변수로 받아와서 해도 되지만 다른 경우가 있을 수 있지 않을까 싶어 객체로 만들어봤는데
너무 과한 생각이였나 싶기도 합니다.

2024-05-02 01:17 UTC, kilian-develop commented on src/main/java/racingcar/CarName.java
> +
@haero77 
엇 인텔리제이 설정에서 Actions on save에 기능이 꺼져있었네요.
프로젝트 생성할 때마다 초기화되는건지... 이전에 설정해놨던 기억이 있는데 풀려있는지 몰랐네요

2024-05-02 01:18 UTC, audrb96 commented on src/main/java/racingcar/CarName.java
> +    }
@haero77 
isValidName()을 만들고 !를 붙이는 것도 생각해봤는데 너무 가독성이 안좋아 보일 것 같았어요.
어떤 네이밍이 좋을지 모르겠네요..

2024-05-02 01:23 UTC, audrb96 commented on src/main/java/racingcar/CarName.java
> +    }
@haero77 
저 같은 경우 DTO같은 경우는 생성자를 열어 놓고 사용합니다.
하지만 도메인과 관련된 클래스의 경우 비즈니스 로직에 영향을 끼치는 부분이 있다보니까.
최대한 new 키워드를 통해 열어두기보다는 create() 함수를 통해 없었던 도메인이 생성되는 시점에만 만들어야 한다! 라고 제한을 두고 싶었어요.
지금보니까 도메인 객체만 제한하고 VO는 생성자를 사용할까 생각이 들기도 하네요.

2024-05-02 01:27 UTC, audrb96 commented on src/main/java/racingcar/CollectionUtils.java
> +}
@haero77 
오 좋은 지적 감사합니다.
spring framework 에서는 abstract 키워드를 붙여 추상 클래스로 만들어서 제한해 뒀네요.

2024-05-02 01:35 UTC, audrb96 commented on src/main/java/racingcar/MoveForwardCondition.java
> +public interface MoveForwardCondition {
@haero77 
좋은 리뷰 감사드립니다.
꼭 하나로 고정될 거라고 보장할 수 없죠.
 그래서 최대한 기능을 제한하기 위해 인터페이스 명칭을 앞으로 움직일 때의 조건만 넣도록 했던 것이기도 했어요.
 @FunctionalInterface를 붙인 이유는 최대한 다른 기능을 추가하지 않기를 바람이였어요. 앞으로 움직이는 조건만 넣을 수 있도록요
 그래서 다른 추가 함수를 만들지 말라는 경고로요.
 다른 함수를 만들고 싶다면 새 인터페이스를 만들어서 추상화해라! 라는 느낌으로요.
 그럴 필요가 전혀없다고 느끼실 수도 있지만, 구현할 때의 저의 생각은 그랬습니다.
 
 제가 잘못 생각한 것일 수도 있어서 제 위 생각에 대한 해로님의 의견이 궁금합니다.

2024-05-02 01:36 UTC, audrb96 commented on src/main/java/racingcar/RacingCar.java
> +    private final MoveForwardCondition moveForwardCondition;
@haero77 
위 action on save가 켜져있으면 자동으로 띄워주던데... 꺼져있는 걸 몰랐네요.

2024-05-02 01:37 UTC, audrb96 commented on src/main/java/racingcar/RacingCar.java
> +    }
@haero77 
네 그래서 이 부분 실수한 것 같아 다음 미션때는 프레젠테이션 레이어와 비즈니스 레이어를 구분지어 구현할 생각입니다.

2024-05-02 01:42 UTC, kilian-develop commented on src/main/java/racingcar/RacingGameNavigation.java
> +public class RacingGameNavigation {
@haero77 
다음 미션 때부터는 이런 클래스들은 abstract를 붙여 제한해보겠습니다.

2024-05-02 01:42 UTC, kilian-develop commented on src/main/java/racingcar/RacingGameNavigation.java
> +}
@haero77 
좋습니다. 근데 다른 문서를 보니 최대한 Constant 클래스를 사용하는걸 지양하고 있더라구요..
그래서 따로 구성하기보다. 프레젠테이션 레이어의 구현 클래스에서 정의할까 합니다..

출처 : https://velog.io/@kasania/Java-Constant-interface

2024-05-02 05:02 UTC, haero77 commented on src/main/java/racingcar/Application.java
> +        RacingCars readyRacingCars = racingGamePlayer.ready();
MVC 패턴과 레이어드 아키텍처는 차이가 약간있어서, MVC 패턴을 먼저 찾아보시면 좋을 것 같습니닷!

2024-05-02 11:10 UTC, haero77 commented on src/main/java/racingcar/CollectionUtils.java
> +}
오오 스프링에서는 그렇게 하고 있군요! 배워갑니다~!

2024-05-02 11:23 UTC, haero77 commented on src/main/java/racingcar/MoveForwardCondition.java
> +public interface MoveForwardCondition {
'다른 추가 함수를 만들지 말라는 경고'가 필요한지, 또 가능한지는 잘 모르겠습니다! 앞으로 움직이는 조건을 만족하는 함수라면 그 함수를 추가하기 위해 인터페이스를 하나 더 만드는 것보다는 해당 인터페이스에 추가되는게 자연스럽다고 생각해요! 지금 같은 경우도 똑같은 기능을 하는 함수를 오버로딩으로 구현하기만 해도 이 애노테이션이 많이 퇴색되죠.

> 다른 함수를 만들고 싶다면 새 인터페이스를 만들어서 추상화해라! 라는 느낌으로요.

'다른 함수를 만들고 싶다면 새 인터페이스를 만들어서 추상화해라!' 라는 컨텍스트라면 주석이 더 와닿을 것 같긴 합니다!

2024-05-02 11:26 UTC, haero77 commented on src/main/java/racingcar/RacingGameNavigation.java
> +}
제시해주신 출처와 제가 남겨드린 코멘트는 많이 다릅니다! 다시 확인해주세요~!

https://en.wikipedia.org/wiki/Constant_interface

![image](https://github.com/talmood/java-racingcar/assets/65555299/d8e8ea3d-17ee-4c7b-860c-b829ba13073d)

2024-05-15 10:34 UTC, merged