[자동차 경주] 해로(김선호) 미션 제출합니다.
talmood/java-racingcar pull request #4
Opened 2024-04-28 12:45 UTC by haero77

2024-04-28 12:56 UTC, haero77 commented on src/main/java/racingcar/model/RandomSingleDigitPicker.java
> +}
`RandomSingleDigitPicker`의 패키지 위치가 애매해서 고민하다가 우선은 model에 두었는데, 아무래도 도메인 모델은 아니다 보니 영 찜찜하네요. 그렇다고 정적 유틸로 보기에는 애매해서 `utils` 보다는 더 핵심에 가까운 model에 두었는데 혹시 리뷰어분들이라면 어느 패키지에 두셨을지 궁금합니다 :)

2024-04-29 14:55 UTC, sc0116 requested changes
안녕하세유 해로 저 짱군데요

코드 재밌게 잘 봤습니다

저는 View 쪽은 오히려 간단하게 했던 것 같은데 해로는 View 쪽을 변경에 유연하게 하셨더라구요! 코멘트 몇개 달아봤습니다! 확인하시구 답글 부탁드려요!

2024-04-29 14:55 UTC, sc0116 commented on src/test/java/racingcar/model/RacingCarTest.java
> +    void invalid_car_name(int numOfMovedForward) {
해당 부분은 -1 값을 제외한 -100, -1_000 두 값은 테스트에 있어 큰 의미가 없는 듯 한데 혹시 두 값도 테스트하신 이유가 있으신가요?? 경계는 -1이면 충분하다고 생각하는데 해로의 생각이 궁금하네요!

2024-04-29 14:55 UTC, sc0116 commented on src/test/java/racingcar/view/ResultViewFormatterTest.java
> +    void formatGameStatus() {
![image](https://github.com/talmood/java-racingcar/assets/47477359/e346b038-837a-4852-bc7d-38c3909bd940)

테스트가 실패하는데 확인 부탁드려요!

2024-04-29 14:55 UTC, sc0116 commented on docs/README.md
> +# 기능 요구 사항
👍👍

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/model/AttemptCount.java
> +    }
이 부분은 테스트를 위해 private 이 아닌 default 로 열어두신 건가요?

만약 그렇다면 해로가 작성해주신 테스트들은 from 을 통한 객체 생성으로도 충분히 작성 가능할 듯 한데 이유가 궁금해요!

2024-04-29 14:55 UTC, sc0116 commented on src/test/java/racingcar/model/AttemptCountTest.java
> +    void invalid_attempt_count(int count) {
-100 은 테스트를 통해 어떤 부분을 얻을 수 있는지에 대해 궁금합니다!

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/model/RacingCarName.java
> +    }
해당 부분은 로직 구조상 0글자 이름을 입력해도 해로가 의도한대로(자동차 이름은 1글자 미만 일 수 없고...) 나오지 않을 것 같아요!

이미 위에서 빈 값에 대한 처리를 해주고 있기 때문에 MIN_NAME_LENGTH 라는 상수는 제 역할을 하지 못할 것 같은데 지우는 건 어떻게 생각하시나용?

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/model/WinnerCars.java
> +    }
RacingCars 에서는 복사해서 넘겨주고 있던데, 이 부분은 그냥 넘기고 있는 이유가 궁금합니다!

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/model/RacingCar.java
> +    }
해로는 자동차들의 각 시작 위치가 다를 수도 있겠다는 상상을 하신 것으로 유추해 보았는데요!

만약 그렇다면 numOfMovedForward 라는 변수명이 알기 어려운 것 같아요!
(이제 생성되었는데 전진 횟수가 0이 아닐 수 있다고???) 라는 생각이 들었는데 혹시 위치를 나타내는 position 으로 자동차 시작 위치를 나타내보는 건 어떠신가요? 물론 제가 잘못 유추한 걸 수도 있겠네여!

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/model/RacingCar.java
> +    private static final int MOVE_FORWARD_LOWER_LIMIT = 4;
저는 해당 기준은 언제든 바뀔 수 있다고 생각을 했는데 RacingCar의 상수로 관리를 하게 되면 변경에 유연한 대처가 어렵지 않을까 하는 생각이 드는데 해로의 생각이 궁금합니다!

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/model/RacingCar.java
> +    }
이렇게 하면 테스트가 쉬워지겠네요!

(여기서부턴 개인적인 취향?이니 무시하셔도 됩니당)
숫자를 뽑아주는 picker와 전진하기 위한 기준을 나타내는 limit은 언제든 변경될 수 있다고 생각해요!
자동차도 엔진이 여러 종류인 것 처럼여!
그래서 전진 여부에 대한 결정을 RacingCar 객체가 하게 되면 전진 기준이 변경될 때마다 RacingCar 도 함께 변경이 되어야 할 것 같은데 해로의 의견을 들어보고 싶어요!

2024-04-29 14:55 UTC, sc0116 commented on src/test/java/racingcar/mock/FakeOutputPrinter.java
> +    }
아무런 동작도 하지 않는다면 Fake 보단 Dummy 에 가깝군요~!

2024-04-29 14:55 UTC, sc0116 commented on src/test/java/racingcar/view/InputViewTest.java
> +                );
이 부분은 해로의 생각을 맞춰보자면 순서가 중요치 않으니 containsExactlyInAnyOrder를 사용한 것 같습니다!

다만 순서가 바뀔 여지가 없다면 오히려 containsExactly를 사용해도 좋지 않을까 생각이 들기도 하네여!

2024-04-29 14:55 UTC, sc0116 commented on src/test/java/racingcar/view/InputViewTest.java
> +    void input_attempt_count(String attemptCountLiteral) {
횟수 입력에 있어 특별한 제한이 없다면 임의의 숫자 하나로만 테스트해도 가치는 충분할 것 같아요!

2024-04-29 14:55 UTC, sc0116 commented on src/test/java/racingcar/view/InputViewTest.java
> +    	Assertions.assertThat(actual.getCount()).isEqualTo(Integer.parseInt(attemptCountLiteral));
actual.getCount() 메서드는 테스트에서만 쓰이더라구요!

그동안 회사에서 틈만 나면 테스트에 대해 서로 의견 공유해서 테스트에 필요한 운영 코드에 대한 해로의 생각을 이미 너무나 잘 알고 있지만!

한편으로는 만들지 않고도 테스트가 가능하면 만들지 않고 테스트 작성해보는 것도 좋아보여요! 물론 취향이라 존중!

2024-04-29 14:55 UTC, sc0116 commented on src/test/java/racingcar/mock/FakeRandomSingleDigitPicker.java
> +public class FakeRandomSingleDigitPicker implements RandomSingleDigitPicker {
저는 mock 처리를 한 반면, 해로는 Fake 처리를 했군요 같은 테스트 다른 방식 신기하네여! 배워갑니둥

2024-04-29 14:55 UTC, sc0116 commented on src/test/java/racingcar/mock/FakeInputReader.java
> +public class FakeInputReader implements InputReader {
이 부분도 입력값에 대한 테스트 방식을 저는 목킹 처리한 반면, 해로는 스텁 처리 했군요!

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/view/InputView.java
> +        }
요거는 사용자 관점에서 하나 남겨봐요! 
자동차경주 개선사항 2분기(^^)
a, b, c 를 해서 입력해도 오류나요ㅠㅠ
그냥 각 이름마다 trim 처리 해주시고 제한 풀어주세요ㅠㅠ

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/view/InputView.java
> +    }
해로는 한 대만 있어도 경주가 시작될 수 있도록 구현하셨네여!
이유가 궁금합니다!

또, 해당 유효성 검증은 단순 입력값 검증보단 중요한 비즈니스 요구사항 이라고 생각해서 
이 부분 뿐만 아니라 RacingCars 에서도 검증해줘야 할 것 같은데 어떻게 생각하시나용?

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/model/AttemptCount.java
> +        if (this.count - 1 < 0) {
this.count < 1 (시도 횟수가 하나 미만인 경우) 라고 되어 있었다면 더 읽기 쉬웠을 거 같아요!

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/model/WinnerCars.java
> +    }
(궁금합니다!)
우승한 자동차들을 나타내는 WinnerCars 객체는 자동차들을 파라미터로 받아서 우승자를 추출하는 것 까지가 WinnerCars 의 역할이라고 저는 생각했는데 해로는 아예 우승자들이 아니면 예외를 처리하도록 해두셨네요!

이렇게 되면 외부에서 우승자들을 정하는 게 되어 버려서 WinnerCars의 존재가 애매해 진다고 생각하는데 이에 대해 해로의 의견이 궁금합니다!

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/model/RandomSingleDigitPicker.java
> +}
일단 저도 model(습관적으로 작성해서 패키지명이 model이 아니라 domain인건 미션적 허용으로 넘어가기^^...) 패키지에 같은 역할을 하는 RandomNumberPicker 를 넣어뒀는데요 

자동차 경주 속에서 도메인 모델들과 핵심적인 협력을 하고 있어서 model 에 두었는데 다른 분들과도 의견 나눠보죠 내일!

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/model/RacingCars.java
> +    }
저는 필터를 하는 부분도 WinnerCars 객체가 하면 좋지 않을까 생각 하는데 해로의 의견이 궁금하네여!

우승자를 가리는 기준이 변경된다고 하더라도(막말로 시작점에서 가장 가까운 자동차가 우승;;;) RacingCars 객체는 변경과 무관해야 한다고 생각해요!

2024-04-29 14:55 UTC, sc0116 commented on src/main/java/racingcar/controller/RacingGameController.java
> +            attemptCount.deductOneCount();
처음 이 코드를 봤을 땐 AttemptCount 가 단순히 입력 값을 받는 역할을 하는 줄 알았는데 바로 아래를 보니 자동차 경주 흐름에서 꽤 다양한 역할을 하고 있네요!

2024-04-29 15:12 UTC, haero77 commented on src/test/java/racingcar/view/ResultViewFormatterTest.java
> +    void formatGameStatus() {
![image](https://github.com/talmood/java-racingcar/assets/65555299/192be537-fba1-4f8e-b0c7-a51e2922ef7c)

오잉 제 환경에서는 잘 실행되는데 혹시 OS 차이 때문일까요?

2024-04-30 15:04 UTC, rueun commented on src/main/java/racingcar/model/WinnerCars.java
> +    }
저는 오히려 우승 자동차를 선정하는 로직은 RacingCars 에 있는게 더 적합하지 않을까 생각이 듭니다.
WinnerCars 객체는 우승한 자동차들을 나타내는 역할을 하고 있고(그냥 그 자체로 우승 자동차들 정보를 담고 있음), 우승 자동차를 선정하는 로직은 레이싱에 참여하는 자동차들을 관리하고 조작하는 역할을 하는 RacingCars 에 있는게 더 적합해보여요..!

2024-05-01 03:48 UTC, haero77 commented on src/test/java/racingcar/model/RacingCarTest.java
> +    void invalid_car_name(int numOfMovedForward) {
맞아요 사실 -1 이면 경계값 테스트로는 충분해요.

이렇게 점점 작은 음수를 파라미터로 넣은 것은 `음수는 제약에 걸리는구나`라는 컨텍스트를 테스트 메서드의 파라미터로 드러내고 싶은 것이 컸습니다. 

그런데 가만 생각해보니, 경계값은 이미 `-1`로도 충분히 검증 가능하고, 컨텍스트를 잘 나타내기 위해 DisplayName도 고심고심하며 지었으므로 굳이 테스트 메서드의 파라미터에서까지 이 컨텍스트를 드러낼 필요가 있을까(혹은 드러나긴 할까)라는 생각이 드네요. 다음 미션부터는 이 부분을 바꿔봐야겠습니다 👍

2024-05-01 03:51 UTC, rueun commented on src/main/java/racingcar/model/RacingCar.java
> +    private final RacingCarName name;
자동차 이름을 뜻하는 name 은 RacingCarName 이라는 객체를 만들었는데, 자동차 이동 거리? 는 객체로 만들지 않고 기본 자료형을 쓴 이유가 따로 있을까요?

2024-05-01 04:00 UTC, rueun commented on src/main/java/racingcar/model/RacingCars.java
> +    }
`List<RacingCar>` 를 복사해서 넘기는 이유가 따로 있는건가요? 복사하지 않고 해당 리스트를 넘기게 되면 받은 쪽에서 조작이 가능할 수도 있어서 그걸 방지하려고 하려는 목적인건지, 아니면 다른 목적이 있는건지 궁금합니다!

2024-05-01 04:00 UTC, haero77 commented on src/main/java/racingcar/model/AttemptCount.java
> +    }
맞아요. 보통 테스트를 위한 데이터를 준비할 때(given), raw한 값 그 자체를 사용하고 싶어서 생성자를 사용했어요. 
테스트에서 validation이나 코드가 포함된 팩토리 메서드를 이용하면 객체 초기화 시점에서 개발자가 원하는 값을 넣기 어려운 경우가 종종 있을 때 빌더를 이용해서 데이터를 준비하곤 하는데, 빌더 없이 데이터를 준비하다보니 default 접근 제어자를 사용했어요.

그런데 가만 생각해보면 위 `AttempCount`같은 경우는 위 같은 케이스는 아니기 때문에, 짱구가 제안해주신 것처럼 `from`을 이용해서 데이터를 준비하는 것도 괜찮아 보이네요. 생성자에 가드(validation)를옮겨놓고 팩토리 메서드를 없애고 생성자로만 데이터를 준비하는 것도 괜찮아 보이고요 :)

2024-05-01 04:01 UTC, haero77 commented on src/test/java/racingcar/model/AttemptCountTest.java
> +    void invalid_attempt_count(int count) {
https://github.com/talmood/java-racingcar/pull/4#discussion_r1585849049 과 비슷한 내용이라 resolve 처리 해둘게요!

2024-05-01 04:06 UTC, rueun commented on src/main/java/racingcar/model/SystemRandomSingleDigitPicker.java
> +}
`RandomSingleDigitPicker` 를 인터페이스로 만든 이유가 궁금해요..!

`SystemRandomSingleDigitPicker` 외에 '다른 방법으로도 랜덤한 숫자를 뽑을 수 있어야 한다.' 는 요구사항이 있을 수도 있어서 그런걸까요?

2024-05-01 04:16 UTC, rueun commented on src/main/java/racingcar/view/ResultViewFormatter.java
> +    }
상수를 사용해서 문자열을 관리하는 이유가 있을까요? 개인적으로는 출력하려는 문자열이 한눈에 보이지 않아서 가독성 측면에서는 살짝 떨어지는 것 같은데, 다른 이점이 있어서 사용을 한건지 의견을 들어보고 싶어요!

2024-05-01 09:25 UTC, haero77 commented on src/main/java/racingcar/model/RacingCarName.java
> +    }
> 해당 부분은 로직 구조상 0글자 이름을 입력해도 해로가 의도한대로(자동차 이름은 1글자 미만 일 수 없고...) 나오지 않을 것 같아요!

맞습니다! 그래서 저 역시 지울까말까 고민을 꽤 했습니다.
다만 자동차 이름의 정책 같은 경우 이후 충분히 변경될 가능성이 있다고 생각했고, 최대 글자수 역시 상수로 관리하고 있기 때문에 통일성을 위해서도 우선 상수로 관리해봤습니다 :)

2024-05-01 09:29 UTC, haero77 commented on src/main/java/racingcar/model/WinnerCars.java
> +    }
우선 getter 자동 생성으로 만들고 복사해서 변경 해준다고 한게 깜빡했군요..

항상 복사해서 넘겨주는 것에 대해서도 한 번 고민을 해봤는데, 
모든 객체를 불변으로 만들지 않는 이상 객체의 상태를 보호하기 위해 항상 참조를 끊는 편이 괜찮겠네요.

항상 복사를 해서 넘겨주는 것에 대해서 짱구는 어떻게 생각하시나요? (복사 혹은 Collections.unmodifiable 에 대한 사용은 어떻게 생각하는지 궁금합니다.)

2024-05-01 09:39 UTC, haero77 commented on src/main/java/racingcar/model/RacingCar.java
> +    }
> 해로는 자동차들의 각 시작 위치가 다를 수도 있겠다는 상상을 하신 것으로 유추해 보았는데요!

이렇게 까지 생각해보진 못했고, '전진 횟수'만 기록하게 하려고 했던게 컸어요.

> (이제 생성되었는데 전진 횟수가 0이 아닐 수 있다고???)라는 생각이 들었는데

'이제 생성되었는데 전진 횟수가 0이 아닐 수 있다'라기 보다는 '전진 횟수'라는 개념이 음수가 될 수 없어서 validation을 넣은 걸로 봐주시면 될 것 같아요.

저 역시 처음에 position도 고려해봤지만 '경주 게임' 인 이상 후진하는 케이스는 일부러 배제했고 명확히 
'전진 횟수'만 상태로 들고 있어도 괜찮겠다 싶어서 이렇게 설계해봤습니당 :)

2024-05-01 09:44 UTC, haero77 commented on src/main/java/racingcar/model/RacingCar.java
> +    private static final int MOVE_FORWARD_LOWER_LIMIT = 4;
저는 오히려 상수로 관리하는 것이 변경에 유연하지 않을까? 라고 생각했어요.
정책 변경이 단순한 경우(예: 던진 횟수가 5이상 일 때 전진)라면 상수값만 바꾸면 되기 때문입니다.

미션의 전진 정책 자체가 복잡했더라면 정책 인터페이스를 만들어서 `전진()` 메시지를 RacingCar에게 던지는 시점에 알맞는 정책 인터페이스의 구현체를 파라미터로 같이 넘겨줄 것 같긴 하네요 :)

짱구가 생각하는 변경에 유연한 대처는 어떤 방식을 생각하신 건지 궁금해요!

2024-05-01 14:04 UTC, haero77 commented on src/main/java/racingcar/model/RacingCar.java
> +    }
>  RacingCar 객체가 하게 되면 전진 기준이 변경될 때마다 RacingCar 도 함께 변경이 되어야 할 것 같은데

맞아요. 확실히 랜덤 숫자 범위가 두 자리 수만 되어도 여기에 변화가 생길 수밖에 없는 구조에요.
안 그래도 짱구가 구현한 것을 보니까 이 전진에 대한 정책 자체를 Engine을 통해 관리하더라고요 👍

움직임에 대한 판단 자체를 RacingCar에 최대한 가깝게 가져가려고 이렇게 했는데, 전진에 대한 정책을 그대로 주입받아도 괜찮았을 거란 생각이 듭니다 👍

2024-05-01 14:04 UTC, haero77 commented on src/test/java/racingcar/mock/FakeOutputPrinter.java
> +    }
오호! 테스트 더블에 대해서 좀 더 공부해보겠습니닷!

2024-05-01 14:07 UTC, haero77 commented on src/test/java/racingcar/view/InputViewTest.java
> +                );
> 다만 순서가 바뀔 여지가 없다면 오히려 `containsExactly`를 사용해도 좋지 않을까 생각이 들기도 하네여!

동의합니다!
여기서는 순서가 상관없는 것을 더 가시적으로 드러내기 위해서 `containsExactlyInAnyOrder`를 사용했어요!

2024-05-01 14:09 UTC, haero77 commented on src/test/java/racingcar/view/InputViewTest.java
> +    void input_attempt_count(String attemptCountLiteral) {
> 숫자 하나로만 테스트해도 가치는 충분할 것 같아요!

동의합니다! 이 테스트는 빡빡한 검증보다는 단순 명세에 가깝다보니, 확실히 숫자하나로도 가치가 충분하다고도 느껴지네요 :)

2024-05-01 14:11 UTC, haero77 commented on src/test/java/racingcar/view/InputViewTest.java
> +    	Assertions.assertThat(actual.getCount()).isEqualTo(Integer.parseInt(attemptCountLiteral));
> 만들지 않고도 테스트가 가능하면 만들지 않고 테스트 작성

만들지 않고도 테스트가 가능한지는 몰랐네요!
`extracting()` 을 사용할 경우도 getter가 필요하기도 해서, 안 만들고 사용해볼 생각은 못해봤네요. 

요건 제가 좀 더 찾아볼게유! 확실히 **만들지 않고도 테스트가 가능하다면** 테스트에서만 사용되는 프로덕션을 남겨둘 필요는 없다고 생각합니닷 🌝

2024-05-01 14:12 UTC, haero77 commented on src/test/java/racingcar/mock/FakeInputReader.java
> +public class FakeInputReader implements InputReader {
짱구는 이부분을 테스트할 때 System의 일부 함수 자체를 목킹처리한 것 같은데 맞으려나요~!

2024-05-01 14:13 UTC, haero77 commented on src/main/java/racingcar/view/InputView.java
> +        }
(끄덕)

확실히 콤마 쓰고 띄어쓰기가 입력의 국룰이긴 하죠.. 
그 정도의 예측 가능한 입력은 서버에서 알아서 처리할 필요도 있는 것 같습니다. (끄덕 x2)

2024-05-01 14:19 UTC, haero77 commented on src/main/java/racingcar/view/InputView.java
> +    }
> 해로는 한 대만 있어도 경주가 시작될 수 있도록 구현하셨네여! 이유가 궁금합니다!

확실히 경주에 포커스를 맞춰보면 두 대 이상이 있어야겠네요. 이 부분은 미처 고려못했습니다 😅

> 또, 해당 유효성 검증은 단순 입력값 검증보단 중요한 비즈니스 요구사항 이라고 생각해서 이 부분 뿐만 아니라 RacingCars 에서도 검증해줘야 할 것 같은데 어떻게 생각하시나용?

네, 우선 이름 입력 자체를 검증해야하므로 입력 뷰단에서도 2개 이상 입력받아야 하는 것을 유지하면서, (입력 검증)
별도로 RacingCars 객체 생성 시 받는 RacingCar의 개수도 2개 이상 받는게 맞다고 생각해요! (비즈니스 로직을 위한 유효성 검증) 예리하게 봐주셨습니다!

2024-05-01 14:40 UTC, haero77 commented on src/main/java/racingcar/model/AttemptCount.java
> +        if (this.count - 1 < 0) {
`횟수 하나를 공제했을 때 음수가 된다면`을 드러내고 싶어서 이렇게 작성했는데,
`현재 횟수가 0회라면 뺄게 없어서 에러를 던질거에요.` 라는 컨텍스트도 괜찮아보이는군요!

2024-05-01 14:46 UTC, haero77 commented on src/main/java/racingcar/model/WinnerCars.java
> +    }
> (궁금합니다!) 우승한 자동차들을 나타내는 WinnerCars 객체는 자동차들을 파라미터로 받아서 우승자를 추출하는 것 까지가 WinnerCars 의 역할이라고 저는 생각했는데 해로는 아예 우승자들이 아니면 예외를 처리하도록 해두셨네요!
> 
> 이렇게 되면 외부에서 우승자들을 정하는 게 되어 버려서 WinnerCars의 존재가 애매해 진다고 생각하는데 이에 대해 해로의 의견이 궁금합니다!

WinnerCars 객체는 이미 생성되는 시점에 우승 자동차가 확정되어야 하므로 우승 자동차를 추출하는 역할은 부여할 수가 없다고 생각했어요. 그래서 우승자가 아니면 객체 생성이 되지 않도록 가드(validation)을 세워두었습니다.

팩토리 메서드에서 `파라미터로 받아서 우승자를 추출`할 수도 있긴 한데, 이것 역시 정적 메서드니까 객체의 역할/책임으로 보기는 어렵겠더라고요. 

결국 우승자를 가져오도록 메시지를 보낼 객체가 자동차의 전진 횟수에 대한 데이터가 연결된 객체로 한정되는데 그러고보니 RacingCars 객체가 메시지를 받는게 제일 괜찮아보이더라고요 :)

> 외부에서 우승자를 정하는 것

RacingCars한테 메시지를 보내는 것은 오히려 내부에 가깝다고 생각했어요!

2024-05-01 14:47 UTC, haero77 commented on src/main/java/racingcar/model/WinnerCars.java
> +    }
> 저는 오히려 우승 자동차를 선정하는 로직은 RacingCars 에 있는게 더 적합하지 않을까 생각이 듭니다.
> 
> WinnerCars 객체는 우승한 자동차들을 나타내는 역할을 하고 있고(그냥 그 자체로 우승 자동차들 정보를 담고 있음), 우승 자동차를 선정하는 로직은 레이싱에 참여하는 자동차들을 관리하고 조작하는 역할을 하는 RacingCars 에 있는게 더 적합해보여요..!

**그냥 그 자체로 우승 자동차들 정보를 담고 있음** 👈 맞습니다 이것을 의도했습니다! 👍

2024-05-01 15:02 UTC, haero77 commented on src/main/java/racingcar/model/RacingCars.java
> +    }
(이 부분은 https://github.com/talmood/java-racingcar/pull/4#discussion_r1586376100 이 코멘트와도 관련 있습니다.)

> 필터를 하는 부분도 WinnerCars 객체가 하면 좋지 않을까

맞아요 저 역시 이 부분을 고민해서 WinnerCars 한테 파라미터를 던져줘서 알아서 뽑히게 하는게 좋을 것 같아서 WinnerCars에 두려고 했습니다. 

그런데 생성자에서 이 과정을 하려고 하니까 생성자에서 코드를 집어넣었어야 했고(불-편),
생성자에 코드를 넣더라도 `우승자를 추출하는 과정`이 메시지를 통해 이루어지는 것이 아니다보니 객체지향적이지 않다고 느꼈어요. 팩토리 메서드에서 하게되면 정적 메소드를 쓰는 시점에서 `우승자를 추출하라` 라는 메시지를 전달할 수 없게 되고요. 

다만 위처럼 구현하는 시점에서 우승자를 가리는 정책이 변경되면 짱구 말대로 RacingCars 코드를 곧바로 수정해야하긴 합니다. **확실히 이 부분은 개선해 볼 필요가 있죠!!**

그래서 제가 미션 후에 곰곰히 계속 생각하다가 좋은 아이디어가 떠올랐지 뭡니까?

1. 우선 `우승차들을 추출해라`라는 메시지는 RacingCars가 그대로 받아요. (왜냐면 현재 이 객체 말고는 메시지를 받을 객체가 없으니까요!)
2. 메시지를 전달 받은 객체가 메시지를 어떻게 수행할 것인지는 객체의 자율성에 따라 RacingCars가 알아서 정할 것이므로, 여기서 WinnerCars의 정적 팩토리 메서드를 호출합니다. 그럼 실제 정책 구현 과정은 팩토리 메서드안에서 일어나겠지만 RacingCars는 본인의 책임을 다하기는 한거니까요! 
3. 위 처럼 구현을 변경하면, 정책이 바뀌더라도 RacingCars의 코드 수정은 일어나지 않게 될 것 같아요. 

위 방법에 대해서 짱구나 은정님은 어떻게 생각하시는지 궁금해지네요 ㅎ 

cc. @rueun

2024-05-01 15:05 UTC, haero77 commented on src/main/java/racingcar/controller/RacingGameController.java
> +            attemptCount.deductOneCount();
AttemptCount가 다양한 역할을 하고 있다고는 생각하지 않습니다! 

카운트의 상태를 관리하는 역할 한 가지만을 수행하고 있다고 생각해요. 책임은 아래 두 가지가 부여되어있고요.

책임1. 카운트가 있는지 확인
책임2. 카운트를 감소

Controller가 다양한 역할을 하고 있다고 말씀하신거라면 그것에는 확실히 동의합니다(끄-덕)

2024-05-01 15:09 UTC, haero77 commented on src/main/java/racingcar/model/RacingCars.java
> +    }
> 해당 리스트를 넘기게 되면 받은 쪽에서 조작이 가능할 수도 있어서 그걸 방지하려고 하려는 목적인건지

맞습니다! 객체 주솟값을 그대로 얻게 되면 그 객체에게 메시지를 보내서 상태가 변경될 수도 있어서 근본적으로 차단하려면 복사해서 넘기는 것이 최선이라고 생각해요!

2024-05-01 15:11 UTC, haero77 commented on src/main/java/racingcar/model/RacingCar.java
> +    private final RacingCarName name;
맞아요 사실 이동거리 역시 객체로 만들까 고민했었는데 날카로우십니다 👍 

우선 RacingCarName은 명확히 글자 수에 대한 정책이 있어야 하므로 응집도를 높이고 싶어서 클래스로 만들었어요.
numOfMovedForward의 경우 RacingCar가 직접 관리하는게 낫다 싶어서 기본 자료형을 사용해봤습니다 :)
(사실 객체로 분리하는게 관리 측면에서 더 좋은 것 같긴합니다)

2024-05-01 15:13 UTC, haero77 commented on src/main/java/racingcar/view/ResultViewFormatter.java
> +    }
맞습니다. 확실히 가독성 측면에서는 손해를 조금 보고 있어요. 그럼에도 상수화 한 것은 실수하기 쉬운 부분이라서 이렇게 만든게 커요. 공백을 넣어야 하는데 실제로는 빈 문자(`""`)를 넣고 있다는 등의 실수를 자주하다 보니 실수 방지 목적으로 부분적으로 상수화를 해봤습니다 :)

2024-05-01 15:17 UTC, haero77 commented on src/main/java/racingcar/model/SystemRandomSingleDigitPicker.java
> +}
우선 `RacingCar 객체 입장에서, [0, 9]에서 랜덤으로 추출한 값이 4 이상일 때 전진한다`를 테스트로 검증하기 위해서 이렇게 한 것이 커요. (이 부분 관해서는 랜덤값을 테스트 하는 방법에 대해 찾아보시면 좋습니다!)

두 번째는 실수 방지의 목적이 있어요.  만약에 int로 파라미터로 넘겨주는 경우 범위를 넘기는 숫자를 넘겨줄 수 있는 실수할 가능성이 생기니까요. 실수를 못하게 미연에 방지하는 것이 좋은 코드라고 생각해서 요새는 최대한 이렇게 코딩하려고 하고 있어요 :)

2024-05-15 10:34 UTC, merged