김민정 - 미션 1. 자동차 경주
talmood/java-racingcar pull request #6
Opened 2024-04-28 20:46 UTC by monsteralover

2024-04-29 13:11 UTC, haero77 reviewed
안녕하세요 민정님, 리뷰어 해로입니다!
간단히 리뷰 남겨봤으니 확인 부탁드릴게요 :)

--- 

미션에 사용된 클래스 중, 상태를 갖는 클래스가 존재하지 않는 것으로 보입니다.

책 객체지향의 사실과 오해에서는 객체를 다음과 같이 설명하고 있는데요,

> (중략) **객체는 구별 가능한 식별자, 특징적인 행동, 변경 가능한 상태를 가진다. 소프트웨어 안에서 객체는 저장된 상태와 실행 가능한 코드를 통해 구현된다.**

객체지향 프로그래밍을 위한 첫 단추로, 우선 상태를 갖는 클래스를 미션에서 활용해보시면 어떨지 조심스럽게 권해드립니다..!

2024-04-29 13:11 UTC, haero77 commented on src/main/java/racingcar/UserInputCondition.java
> +}
(의도가 궁금해요!)

UserInputCondition의 구현체는 하난데, UserInputCondition를 별도로 인터페이스로 선언하신 의도가 궁금합니다 :)

2024-04-29 13:11 UTC, haero77 commented on src/main/java/racingcar/UserInput.java
> +    private static class validateUserInput {
(네이밍 관례)

클래스명이 소문자로 시작하고 있고, 동사로 시작하고 있습니다!
 [이펙티브 자바 item 68. 일반적으로 통용되는 명명 규칙을 따르라](https://jake-seo-dev.tistory.com/563#%ED%--%B-%EB%-E%--%EC%-A%A-%EC%--%--%--%EC%-D%B-%ED%--%B-%ED%-E%--%EC%-D%B-%EC%-A%A-)를 참고해보시면 좋을 것 같아요 :)

2024-04-29 13:11 UTC, haero77 commented on src/main/java/racingcar/CarDrive.java
> +    private void runCars(Map<String, Integer> mileageForCar) {
(코드 스타일)

현재 개행 기준이 일관적이지 않습니다! 
자동 정렬 단축키를 활용하거나, 커밋 시 자동 정렬 옵션을 적극적으로 사용해보셔도 좋을 것 같아요!

2024-04-29 13:11 UTC, haero77 commented on src/main/java/racingcar/ScoreWinner.java
> +    }
(의도가 궁금합니다!)

현재 ScoreWinner는 많은 기능이 static 메서드와 인스턴스 메서드로 나뉘어 있는 형태입니다.
민정님의 static과 인스턴스 메서드를 나눠서 사용하시는 기준이 궁금합니다 :)

2024-04-29 13:11 UTC, haero77 commented on src/main/java/racingcar/ScoreWinner.java
> +        }
(이런 방법도 있어요!)

`Collector.joining(...)`을 조금 더 활용해보면 `winnerString.endsWith(",")`와 같은 작업을 없앨 수 있을 것 같습니다!

2024-04-30 01:29 UTC, sc0116 requested changes
민정님 안녕하세유 저 짱군데요

어제 리뷰 달아드리려 했는데 자버려서 늦었지만 지금 리뷰 남겨요!

첫 미션은 어떠셨나요? 전 오랜만에 하니 더 설렜네요^^
저는 이번 첫 미션에서는 책임과 행위를 기반으로 객체간 협력에 대해 설계해보자! 라는 목표가 있었는데 민정님은 이번 미션에서 어떤 것을 중점적으로 생각하셨는지 궁금해요!

2024-04-30 01:29 UTC, sc0116 commented on src/main/java/racingcar/UserInputCondition.java
> +public interface UserInputCondition {
민정님께서는 경주에 필요한 입력값을 받는 부분을 추상화하셨네요!!! 추후 콘솔 입력이 아닌 파일이나 Json 등으로 입력 조건이 변경되는 부분을 염두에 두고 하신건지 생각이 궁금합니다!!

2024-04-30 01:29 UTC, sc0116 commented on src/main/java/racingcar/UserInput.java
> +            String[] names = carNames.split(",");
만약 경주에 참여한 자동차 이름 입력값이
"a, b , c   "라고 하면 자동차의 이름은
"a", " b ", " c   " 이렇게 공백이 들어가게 될 것 같은데유!
각 이름에 대해 양쪽 공백을 제거해주면 어떨까 하는데 민정님 의견은 어떠신가유??

2024-04-30 01:29 UTC, sc0116 commented on src/main/java/racingcar/CarDrive.java
> +    static boolean canGoForward(int randomNumber) {
CarDrive의 canGoForward 정적 메서드 또는 ScoreWinner의 정적 메서드들은 다른 객체에게 역할을 부여해보는 건 어떠신가요??

부모 객체에 있는 정적 변수 혹은 메서드가 아닌 상속 받은 자식 객체나 구현한 구현 객체에 해당 코드들이 존재하게 되면 추상화한 Drive나 Score를 사용할 때 어떤 하위 객체를 사용하냐에 따라 제약이 생길 수도 있다고 생각해요!

혹시 민정님은 어떻게 생각하시나요! 궁금합니다!

2024-04-30 01:29 UTC, sc0116 commented on src/main/java/racingcar/ScoreWinner.java
> +                .collect(Collectors.joining());
joining 메서드에 구분자를 입력하면 보다 간편하게 문자열들을 조인할 수 있어요!

그렇게 되면 아래 마지막 콤마(,)에 대한 처리 로직도 고려하지 않아도 될 것 같아서 민정님을 편하게 할 것 같아유!!

2024-05-15 10:35 UTC, merged